name: KiCad Library
description: Create or edit a KiCad Library
title: "[KiCad]: "
labels: ["libgen"]
projects: []
assignees:
  - Datenkrake
body:
  - type: markdown
    attributes:
      value: |
        Create or edit a component in the KiCad Library.

  - type: input
    id: partnumber
    attributes:
      label: Part Number
      description: LCSC or Library Part Number(s)
      placeholder: ex. "C1234" or "C2345, B3D012AB3"
    validations:
      required: true

  - type: checkboxes
    id: update-from-lcsc
    attributes:
      label: LCSC Update
      description: Check this box to fetch the latest data from LCSC and update the component in the library.
      options:
        - label: Overwrite existing data, incl. Symbol and Footprint files
          required: false

  - type: textarea
    id: parameters
    attributes:
      label: Set Value(s)
      description: Set one or more parameters for the component.
      placeholder: Keep what was there, just add the value(s) you want to set.
      value:  "'Symbols': '',<br>'Footprints': '',<br>'Datasheet': '',<br>'Description': '',<br>'Category': '',<br>'Subcategory': '',<br>'value1': '',<br>'value2': '',<br>'value3': '',<br>'value4': ''"
    validations:
      required: false
  
  
