name: Update Stock and Price Data from JLCPARTS (Daily)

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  clone-install-execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Download Files
      run: wget https://yaqwsx.github.io/jlcparts/data/cache.zip https://yaqwsx.github.io/jlcparts/data/cache.z0{1..8} || true
      working-directory: ${{ github.workspace }}

    - name: Unzip Files
      run: 7z x cache.zip
      working-directory: ${{ github.workspace }}

    - name: Run your action here
      id: run-script
      run: |
        output=$(python _kicad-libgen/refresh_jlcdata.py)

    - name: Commit and Push Changes
      run: |
        git config --global user.email "refried08oatmeal@icloud.com"
        git config --global user.name "Datenkrake"
        git pull
        git add .
        git commit -m "jlcparts cache db update"
        git push
      working-directory: ${{ github.workspace }}
